#!/bin/bash
PROJECT_ID="aeb8d233-5976-4ab8-967d-77ec6ce89ebf"
API="http://localhost:3000/api/projects/$PROJECT_ID/migrations"

post() {
  curl -s -X POST "$API" -H "Content-Type: application/json" -d "$1" > /dev/null
  echo "  Created: $2"
}

echo "Creating table migrations..."

# V1
post '{"description":"Create extensions","sqlContent":"CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";\nCREATE EXTENSION IF NOT EXISTS \"pgcrypto\";\nCREATE EXTENSION IF NOT EXISTS \"pg_trgm\";"}' "V1"

# V2
post '{"description":"Create users table","sqlContent":"CREATE TABLE users (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  email VARCHAR(255) NOT NULL UNIQUE,\n  username VARCHAR(100) NOT NULL UNIQUE,\n  password_hash VARCHAR(255) NOT NULL,\n  first_name VARCHAR(100),\n  last_name VARCHAR(100),\n  phone VARCHAR(20),\n  avatar_url TEXT,\n  email_verified BOOLEAN DEFAULT FALSE,\n  is_active BOOLEAN DEFAULT TRUE,\n  last_login_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_users_email ON users(email);\nCREATE INDEX idx_users_username ON users(username);\nCREATE INDEX idx_users_email_trgm ON users USING gin(email gin_trgm_ops);"}' "V2"

# V3
post '{"description":"Create user addresses table","sqlContent":"CREATE TABLE user_addresses (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  label VARCHAR(50) DEFAULT '\''home'\'',\n  street_line_1 VARCHAR(255) NOT NULL,\n  street_line_2 VARCHAR(255),\n  city VARCHAR(100) NOT NULL,\n  state VARCHAR(100),\n  postal_code VARCHAR(20) NOT NULL,\n  country_code CHAR(2) NOT NULL DEFAULT '\''US'\'',\n  is_default BOOLEAN DEFAULT FALSE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_user_addresses_user_id ON user_addresses(user_id);"}' "V3"

# V4
post '{"description":"Create categories table","sqlContent":"CREATE TABLE categories (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  parent_id UUID REFERENCES categories(id) ON DELETE SET NULL,\n  name VARCHAR(255) NOT NULL,\n  slug VARCHAR(255) NOT NULL UNIQUE,\n  description TEXT,\n  image_url TEXT,\n  sort_order INTEGER DEFAULT 0,\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_categories_parent_id ON categories(parent_id);\nCREATE INDEX idx_categories_slug ON categories(slug);"}' "V4"

# V5
post '{"description":"Create brands table","sqlContent":"CREATE TABLE brands (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(255) NOT NULL UNIQUE,\n  slug VARCHAR(255) NOT NULL UNIQUE,\n  description TEXT,\n  logo_url TEXT,\n  website_url TEXT,\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_brands_slug ON brands(slug);"}' "V5"

# V6
post '{"description":"Create products table","sqlContent":"CREATE TABLE products (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,\n  brand_id UUID REFERENCES brands(id) ON DELETE SET NULL,\n  sku VARCHAR(100) NOT NULL UNIQUE,\n  name VARCHAR(500) NOT NULL,\n  slug VARCHAR(500) NOT NULL UNIQUE,\n  description TEXT,\n  short_description VARCHAR(1000),\n  base_price NUMERIC(12,2) NOT NULL,\n  compare_at_price NUMERIC(12,2),\n  cost_price NUMERIC(12,2),\n  weight_grams INTEGER,\n  is_active BOOLEAN DEFAULT TRUE,\n  is_featured BOOLEAN DEFAULT FALSE,\n  is_digital BOOLEAN DEFAULT FALSE,\n  meta_title VARCHAR(255),\n  meta_description VARCHAR(500),\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_products_category_id ON products(category_id);\nCREATE INDEX idx_products_brand_id ON products(brand_id);\nCREATE INDEX idx_products_sku ON products(sku);\nCREATE INDEX idx_products_slug ON products(slug);\nCREATE INDEX idx_products_name_trgm ON products USING gin(name gin_trgm_ops);"}' "V6"

# V7
post '{"description":"Create product variants table","sqlContent":"CREATE TABLE product_variants (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,\n  sku VARCHAR(100) NOT NULL UNIQUE,\n  name VARCHAR(255) NOT NULL,\n  price_override NUMERIC(12,2),\n  weight_grams_override INTEGER,\n  stock_quantity INTEGER NOT NULL DEFAULT 0,\n  low_stock_threshold INTEGER DEFAULT 5,\n  is_active BOOLEAN DEFAULT TRUE,\n  sort_order INTEGER DEFAULT 0,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_product_variants_product_id ON product_variants(product_id);"}' "V7"

# V8
post '{"description":"Create product images table","sqlContent":"CREATE TABLE product_images (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,\n  variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL,\n  url TEXT NOT NULL,\n  alt_text VARCHAR(255),\n  sort_order INTEGER DEFAULT 0,\n  is_primary BOOLEAN DEFAULT FALSE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_product_images_product_id ON product_images(product_id);"}' "V8"

# V9
post '{"description":"Create product attributes table","sqlContent":"CREATE TABLE product_attributes (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(100) NOT NULL UNIQUE,\n  display_name VARCHAR(255) NOT NULL,\n  attribute_type VARCHAR(20) NOT NULL DEFAULT '\''text'\'',\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE product_attribute_values (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,\n  attribute_id UUID NOT NULL REFERENCES product_attributes(id) ON DELETE CASCADE,\n  value TEXT NOT NULL,\n  UNIQUE(product_id, attribute_id)\n);\n\nCREATE INDEX idx_pav_product_id ON product_attribute_values(product_id);\nCREATE INDEX idx_pav_attribute_id ON product_attribute_values(attribute_id);"}' "V9"

# V10
post '{"description":"Create product tags table","sqlContent":"CREATE TABLE tags (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(100) NOT NULL UNIQUE,\n  slug VARCHAR(100) NOT NULL UNIQUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE product_tags (\n  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,\n  tag_id UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,\n  PRIMARY KEY (product_id, tag_id)\n);\n\nCREATE INDEX idx_product_tags_tag_id ON product_tags(tag_id);"}' "V10"

# V11
post '{"description":"Create inventory locations table","sqlContent":"CREATE TABLE inventory_locations (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(255) NOT NULL,\n  code VARCHAR(50) NOT NULL UNIQUE,\n  address_line_1 VARCHAR(255),\n  city VARCHAR(100),\n  state VARCHAR(100),\n  country_code CHAR(2) DEFAULT '\''US'\'',\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE inventory_levels (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  variant_id UUID NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,\n  location_id UUID NOT NULL REFERENCES inventory_locations(id) ON DELETE CASCADE,\n  quantity INTEGER NOT NULL DEFAULT 0,\n  reserved_quantity INTEGER NOT NULL DEFAULT 0,\n  UNIQUE(variant_id, location_id)\n);\n\nCREATE INDEX idx_inventory_levels_variant ON inventory_levels(variant_id);\nCREATE INDEX idx_inventory_levels_location ON inventory_levels(location_id);"}' "V11"

# V12
post '{"description":"Create shopping carts table","sqlContent":"CREATE TABLE shopping_carts (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  user_id UUID REFERENCES users(id) ON DELETE SET NULL,\n  session_id VARCHAR(255),\n  currency_code CHAR(3) DEFAULT '\''USD'\'',\n  expires_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE cart_items (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  cart_id UUID NOT NULL REFERENCES shopping_carts(id) ON DELETE CASCADE,\n  variant_id UUID NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,\n  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),\n  unit_price NUMERIC(12,2) NOT NULL,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  UNIQUE(cart_id, variant_id)\n);\n\nCREATE INDEX idx_shopping_carts_user_id ON shopping_carts(user_id);\nCREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);"}' "V12"

# V13
post '{"description":"Create orders table","sqlContent":"CREATE TYPE order_status AS ENUM (\n  '\''pending'\'', '\''confirmed'\'', '\''processing'\'',\n  '\''shipped'\'', '\''delivered'\'', '\''cancelled'\'', '\''refunded'\''\n);\n\nCREATE TABLE orders (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  user_id UUID REFERENCES users(id) ON DELETE SET NULL,\n  order_number VARCHAR(50) NOT NULL UNIQUE,\n  status order_status NOT NULL DEFAULT '\''pending'\'',\n  subtotal NUMERIC(12,2) NOT NULL,\n  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,\n  shipping_amount NUMERIC(12,2) NOT NULL DEFAULT 0,\n  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,\n  total NUMERIC(12,2) NOT NULL,\n  currency_code CHAR(3) DEFAULT '\''USD'\'',\n  notes TEXT,\n  shipping_address_json JSONB,\n  billing_address_json JSONB,\n  placed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  confirmed_at TIMESTAMP WITH TIME ZONE,\n  shipped_at TIMESTAMP WITH TIME ZONE,\n  delivered_at TIMESTAMP WITH TIME ZONE,\n  cancelled_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_orders_user_id ON orders(user_id);\nCREATE INDEX idx_orders_status ON orders(status);\nCREATE INDEX idx_orders_order_number ON orders(order_number);\nCREATE INDEX idx_orders_placed_at ON orders(placed_at DESC);"}' "V13"

# V14
post '{"description":"Create order items table","sqlContent":"CREATE TABLE order_items (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  product_id UUID REFERENCES products(id) ON DELETE SET NULL,\n  variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL,\n  product_name VARCHAR(500) NOT NULL,\n  variant_name VARCHAR(255),\n  sku VARCHAR(100) NOT NULL,\n  quantity INTEGER NOT NULL CHECK (quantity > 0),\n  unit_price NUMERIC(12,2) NOT NULL,\n  total_price NUMERIC(12,2) NOT NULL,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_order_items_order_id ON order_items(order_id);\nCREATE INDEX idx_order_items_product_id ON order_items(product_id);"}' "V14"

# V15
post '{"description":"Create payments table","sqlContent":"CREATE TYPE payment_status AS ENUM (\n  '\''pending'\'', '\''authorized'\'', '\''captured'\'',\n  '\''failed'\'', '\''refunded'\'', '\''partially_refunded'\''\n);\n\nCREATE TYPE payment_method AS ENUM (\n  '\''credit_card'\'', '\''debit_card'\'', '\''paypal'\'',\n  '\''bank_transfer'\'', '\''crypto'\'', '\''gift_card'\''\n);\n\nCREATE TABLE payments (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  payment_method payment_method NOT NULL,\n  status payment_status NOT NULL DEFAULT '\''pending'\'',\n  amount NUMERIC(12,2) NOT NULL,\n  currency_code CHAR(3) DEFAULT '\''USD'\'',\n  gateway_transaction_id VARCHAR(255),\n  gateway_response JSONB,\n  paid_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_payments_order_id ON payments(order_id);\nCREATE INDEX idx_payments_status ON payments(status);"}' "V15"

# V16
post '{"description":"Create shipping methods and shipments tables","sqlContent":"CREATE TABLE shipping_methods (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(255) NOT NULL,\n  carrier VARCHAR(100) NOT NULL,\n  estimated_days_min INTEGER,\n  estimated_days_max INTEGER,\n  base_rate NUMERIC(12,2) NOT NULL,\n  rate_per_kg NUMERIC(12,2) DEFAULT 0,\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE shipments (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  shipping_method_id UUID REFERENCES shipping_methods(id),\n  tracking_number VARCHAR(255),\n  tracking_url TEXT,\n  status VARCHAR(50) DEFAULT '\''pending'\'',\n  shipped_at TIMESTAMP WITH TIME ZONE,\n  estimated_delivery_at TIMESTAMP WITH TIME ZONE,\n  delivered_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_shipments_order_id ON shipments(order_id);\nCREATE INDEX idx_shipments_tracking ON shipments(tracking_number);"}' "V16"

# V17
post '{"description":"Create coupons and discounts tables","sqlContent":"CREATE TYPE discount_type AS ENUM ('\''percentage'\'', '\''fixed_amount'\'', '\''free_shipping'\'');\n\nCREATE TABLE coupons (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  code VARCHAR(50) NOT NULL UNIQUE,\n  description TEXT,\n  discount_type discount_type NOT NULL,\n  discount_value NUMERIC(12,2) NOT NULL,\n  minimum_order_amount NUMERIC(12,2),\n  maximum_discount_amount NUMERIC(12,2),\n  usage_limit INTEGER,\n  usage_count INTEGER DEFAULT 0,\n  per_user_limit INTEGER DEFAULT 1,\n  starts_at TIMESTAMP WITH TIME ZONE,\n  expires_at TIMESTAMP WITH TIME ZONE,\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE order_coupons (\n  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  coupon_id UUID NOT NULL REFERENCES coupons(id),\n  discount_applied NUMERIC(12,2) NOT NULL,\n  PRIMARY KEY (order_id, coupon_id)\n);\n\nCREATE INDEX idx_coupons_code ON coupons(code);\nCREATE INDEX idx_coupons_expires ON coupons(expires_at);"}' "V17"

# V18
post '{"description":"Create product reviews table","sqlContent":"CREATE TABLE product_reviews (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,\n  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),\n  title VARCHAR(255),\n  body TEXT,\n  is_verified_purchase BOOLEAN DEFAULT FALSE,\n  is_approved BOOLEAN DEFAULT FALSE,\n  helpful_count INTEGER DEFAULT 0,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  UNIQUE(product_id, user_id)\n);\n\nCREATE INDEX idx_reviews_product_id ON product_reviews(product_id);\nCREATE INDEX idx_reviews_user_id ON product_reviews(user_id);\nCREATE INDEX idx_reviews_rating ON product_reviews(rating);"}' "V18"

# V19
post '{"description":"Create wishlists table","sqlContent":"CREATE TABLE wishlists (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  name VARCHAR(255) DEFAULT '\''My Wishlist'\'',\n  is_public BOOLEAN DEFAULT FALSE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE wishlist_items (\n  wishlist_id UUID NOT NULL REFERENCES wishlists(id) ON DELETE CASCADE,\n  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,\n  added_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  PRIMARY KEY (wishlist_id, product_id)\n);\n\nCREATE INDEX idx_wishlists_user_id ON wishlists(user_id);"}' "V19"

# V20
post '{"description":"Create notifications table","sqlContent":"CREATE TYPE notification_channel AS ENUM ('\''email'\'', '\''sms'\'', '\''push'\'', '\''in_app'\'');\n\nCREATE TABLE notifications (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  channel notification_channel NOT NULL DEFAULT '\''in_app'\'',\n  type VARCHAR(100) NOT NULL,\n  title VARCHAR(255) NOT NULL,\n  body TEXT,\n  data JSONB,\n  is_read BOOLEAN DEFAULT FALSE,\n  read_at TIMESTAMP WITH TIME ZONE,\n  sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_notifications_user_id ON notifications(user_id);\nCREATE INDEX idx_notifications_unread ON notifications(user_id) WHERE is_read = FALSE;"}' "V20"

# V21
post '{"description":"Create audit log table","sqlContent":"CREATE TABLE audit_log (\n  id BIGSERIAL PRIMARY KEY,\n  user_id UUID REFERENCES users(id) ON DELETE SET NULL,\n  entity_type VARCHAR(100) NOT NULL,\n  entity_id UUID NOT NULL,\n  action VARCHAR(50) NOT NULL,\n  old_values JSONB,\n  new_values JSONB,\n  ip_address INET,\n  user_agent TEXT,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_audit_log_entity ON audit_log(entity_type, entity_id);\nCREATE INDEX idx_audit_log_user ON audit_log(user_id);\nCREATE INDEX idx_audit_log_created ON audit_log(created_at DESC);"}' "V21"

# V22
post '{"description":"Create user sessions table","sqlContent":"CREATE TABLE user_sessions (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  token_hash VARCHAR(255) NOT NULL UNIQUE,\n  ip_address INET,\n  user_agent TEXT,\n  last_active_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);\nCREATE INDEX idx_user_sessions_token ON user_sessions(token_hash);\nCREATE INDEX idx_user_sessions_expires ON user_sessions(expires_at);"}' "V22"

# V23
post '{"description":"Create tax rates table","sqlContent":"CREATE TABLE tax_zones (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(255) NOT NULL,\n  country_code CHAR(2) NOT NULL,\n  state_code VARCHAR(10),\n  postal_code_pattern VARCHAR(50),\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE tax_rates (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  zone_id UUID NOT NULL REFERENCES tax_zones(id) ON DELETE CASCADE,\n  name VARCHAR(100) NOT NULL,\n  rate NUMERIC(6,4) NOT NULL,\n  is_compound BOOLEAN DEFAULT FALSE,\n  priority INTEGER DEFAULT 0,\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_tax_zones_country ON tax_zones(country_code);\nCREATE INDEX idx_tax_rates_zone ON tax_rates(zone_id);"}' "V23"

# V24
post '{"description":"Create warehouses and fulfillment tables","sqlContent":"CREATE TABLE warehouses (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(255) NOT NULL,\n  code VARCHAR(50) NOT NULL UNIQUE,\n  address JSONB NOT NULL,\n  is_active BOOLEAN DEFAULT TRUE,\n  priority INTEGER DEFAULT 0,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE fulfillment_orders (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  warehouse_id UUID NOT NULL REFERENCES warehouses(id),\n  status VARCHAR(50) DEFAULT '\''pending'\'',\n  assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  picked_at TIMESTAMP WITH TIME ZONE,\n  packed_at TIMESTAMP WITH TIME ZONE,\n  shipped_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_fulfillment_order_id ON fulfillment_orders(order_id);\nCREATE INDEX idx_fulfillment_warehouse ON fulfillment_orders(warehouse_id);"}' "V24"

# V25
post '{"description":"Create returns and refunds tables","sqlContent":"CREATE TYPE return_status AS ENUM (\n  '\''requested'\'', '\''approved'\'', '\''received'\'',\n  '\''inspected'\'', '\''refunded'\'', '\''rejected'\''\n);\n\nCREATE TABLE returns (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  user_id UUID NOT NULL REFERENCES users(id),\n  status return_status NOT NULL DEFAULT '\''requested'\'',\n  reason VARCHAR(255) NOT NULL,\n  notes TEXT,\n  requested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  approved_at TIMESTAMP WITH TIME ZONE,\n  received_at TIMESTAMP WITH TIME ZONE,\n  refunded_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE return_items (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  return_id UUID NOT NULL REFERENCES returns(id) ON DELETE CASCADE,\n  order_item_id UUID NOT NULL REFERENCES order_items(id),\n  quantity INTEGER NOT NULL CHECK (quantity > 0),\n  refund_amount NUMERIC(12,2) NOT NULL,\n  condition VARCHAR(50)\n);\n\nCREATE INDEX idx_returns_order_id ON returns(order_id);\nCREATE INDEX idx_return_items_return ON return_items(return_id);"}' "V25"

# V26
post '{"description":"Create gift cards table","sqlContent":"CREATE TABLE gift_cards (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  code VARCHAR(50) NOT NULL UNIQUE,\n  initial_balance NUMERIC(12,2) NOT NULL,\n  current_balance NUMERIC(12,2) NOT NULL,\n  currency_code CHAR(3) DEFAULT '\''USD'\'',\n  purchaser_id UUID REFERENCES users(id),\n  recipient_email VARCHAR(255),\n  recipient_name VARCHAR(255),\n  message TEXT,\n  is_active BOOLEAN DEFAULT TRUE,\n  expires_at TIMESTAMP WITH TIME ZONE,\n  activated_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE gift_card_transactions (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  gift_card_id UUID NOT NULL REFERENCES gift_cards(id),\n  order_id UUID REFERENCES orders(id),\n  amount NUMERIC(12,2) NOT NULL,\n  balance_after NUMERIC(12,2) NOT NULL,\n  type VARCHAR(20) NOT NULL,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_gift_cards_code ON gift_cards(code);\nCREATE INDEX idx_gc_transactions ON gift_card_transactions(gift_card_id);"}' "V26"

# V27
post '{"description":"Create email templates table","sqlContent":"CREATE TABLE email_templates (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  name VARCHAR(100) NOT NULL UNIQUE,\n  subject VARCHAR(500) NOT NULL,\n  html_body TEXT NOT NULL,\n  text_body TEXT,\n  variables JSONB DEFAULT '\''[]'\''::jsonb,\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE email_log (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  template_id UUID REFERENCES email_templates(id),\n  recipient_email VARCHAR(255) NOT NULL,\n  subject VARCHAR(500) NOT NULL,\n  status VARCHAR(20) DEFAULT '\''queued'\'',\n  sent_at TIMESTAMP WITH TIME ZONE,\n  error_message TEXT,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_email_log_recipient ON email_log(recipient_email);\nCREATE INDEX idx_email_log_status ON email_log(status);"}' "V27"

# V28
post '{"description":"Create page content and CMS tables","sqlContent":"CREATE TABLE pages (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  title VARCHAR(500) NOT NULL,\n  slug VARCHAR(500) NOT NULL UNIQUE,\n  content TEXT,\n  meta_title VARCHAR(255),\n  meta_description VARCHAR(500),\n  is_published BOOLEAN DEFAULT FALSE,\n  published_at TIMESTAMP WITH TIME ZONE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE banners (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  title VARCHAR(255) NOT NULL,\n  image_url TEXT NOT NULL,\n  link_url TEXT,\n  position VARCHAR(50) DEFAULT '\''homepage'\'',\n  sort_order INTEGER DEFAULT 0,\n  starts_at TIMESTAMP WITH TIME ZONE,\n  ends_at TIMESTAMP WITH TIME ZONE,\n  is_active BOOLEAN DEFAULT TRUE,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_pages_slug ON pages(slug);\nCREATE INDEX idx_banners_position ON banners(position);"}' "V28"

# V29
post '{"description":"Create search history and analytics tables","sqlContent":"CREATE TABLE search_queries (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  user_id UUID REFERENCES users(id) ON DELETE SET NULL,\n  query_text VARCHAR(500) NOT NULL,\n  results_count INTEGER DEFAULT 0,\n  clicked_product_id UUID REFERENCES products(id) ON DELETE SET NULL,\n  session_id VARCHAR(255),\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE product_views (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,\n  user_id UUID REFERENCES users(id) ON DELETE SET NULL,\n  session_id VARCHAR(255),\n  referrer TEXT,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_search_queries_text ON search_queries(query_text);\nCREATE INDEX idx_search_queries_created ON search_queries(created_at DESC);\nCREATE INDEX idx_product_views_product ON product_views(product_id);\nCREATE INDEX idx_product_views_created ON product_views(created_at DESC);"}' "V29"

# V30
post '{"description":"Create webhook and integration tables","sqlContent":"CREATE TABLE webhooks (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  url TEXT NOT NULL,\n  secret VARCHAR(255) NOT NULL,\n  events TEXT[] NOT NULL,\n  is_active BOOLEAN DEFAULT TRUE,\n  last_triggered_at TIMESTAMP WITH TIME ZONE,\n  failure_count INTEGER DEFAULT 0,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE TABLE webhook_deliveries (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n  webhook_id UUID NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,\n  event VARCHAR(100) NOT NULL,\n  payload JSONB NOT NULL,\n  response_status INTEGER,\n  response_body TEXT,\n  success BOOLEAN DEFAULT FALSE,\n  duration_ms INTEGER,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nCREATE INDEX idx_webhook_deliveries_webhook ON webhook_deliveries(webhook_id);\nCREATE INDEX idx_webhook_deliveries_created ON webhook_deliveries(created_at DESC);"}' "V30"

# V31
post '{"description":"Create settings and configuration tables","sqlContent":"CREATE TABLE store_settings (\n  key VARCHAR(255) PRIMARY KEY,\n  value JSONB NOT NULL,\n  description TEXT,\n  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n);\n\nINSERT INTO store_settings (key, value, description) VALUES\n  ('\''store_name'\'', '\"My E-Commerce Store\"', '\''Name of the store'\''),\n  ('\''store_currency'\'', '\"USD\"', '\''Default currency'\''),\n  ('\''store_timezone'\'', '\"America/New_York\"', '\''Store timezone'\''),\n  ('\''tax_included'\'', '\''false'\'', '\''Whether prices include tax'\''),\n  ('\''inventory_tracking'\'', '\''true'\'', '\''Enable inventory tracking'\''),\n  ('\''low_stock_threshold'\'', '\''10'\'', '\''Default low stock alert threshold'\''),\n  ('\''order_number_prefix'\'', '\"ORD-\"', '\''Prefix for order numbers'\''),\n  ('\''allow_guest_checkout'\'', '\''true'\'', '\''Allow checkout without account'\'');"}' "V31"

echo ""
echo "Creating view migrations..."

# V32 - Views start
post '{"description":"Create product catalog view","sqlContent":"CREATE OR REPLACE VIEW v_product_catalog AS\nSELECT\n  p.id,\n  p.sku,\n  p.name,\n  p.slug,\n  p.description,\n  p.short_description,\n  p.base_price,\n  p.compare_at_price,\n  p.is_active,\n  p.is_featured,\n  c.name AS category_name,\n  c.slug AS category_slug,\n  b.name AS brand_name,\n  b.slug AS brand_slug,\n  COALESCE(img.url, '\''/images/placeholder.png'\'') AS primary_image_url,\n  COALESCE(rv.avg_rating, 0) AS avg_rating,\n  COALESCE(rv.review_count, 0) AS review_count,\n  COALESCE(inv.total_stock, 0) AS total_stock,\n  p.created_at,\n  p.updated_at\nFROM products p\nLEFT JOIN categories c ON c.id = p.category_id\nLEFT JOIN brands b ON b.id = p.brand_id\nLEFT JOIN LATERAL (\n  SELECT url FROM product_images pi\n  WHERE pi.product_id = p.id AND pi.is_primary = TRUE\n  LIMIT 1\n) img ON TRUE\nLEFT JOIN LATERAL (\n  SELECT AVG(rating)::NUMERIC(3,2) AS avg_rating, COUNT(*) AS review_count\n  FROM product_reviews pr\n  WHERE pr.product_id = p.id AND pr.is_approved = TRUE\n) rv ON TRUE\nLEFT JOIN LATERAL (\n  SELECT SUM(pv2.stock_quantity) AS total_stock\n  FROM product_variants pv2\n  WHERE pv2.product_id = p.id AND pv2.is_active = TRUE\n) inv ON TRUE;"}' "V32"

# V33
post '{"description":"Create order summary view","sqlContent":"CREATE OR REPLACE VIEW v_order_summary AS\nSELECT\n  o.id,\n  o.order_number,\n  o.status,\n  o.subtotal,\n  o.tax_amount,\n  o.shipping_amount,\n  o.discount_amount,\n  o.total,\n  o.currency_code,\n  o.placed_at,\n  o.shipped_at,\n  o.delivered_at,\n  u.email AS customer_email,\n  u.first_name || '\'' '\'' || u.last_name AS customer_name,\n  COUNT(oi.id) AS item_count,\n  SUM(oi.quantity) AS total_units,\n  p.status AS payment_status,\n  p.payment_method,\n  s.tracking_number,\n  s.status AS shipment_status\nFROM orders o\nLEFT JOIN users u ON u.id = o.user_id\nLEFT JOIN order_items oi ON oi.order_id = o.id\nLEFT JOIN LATERAL (\n  SELECT status, payment_method FROM payments\n  WHERE order_id = o.id ORDER BY created_at DESC LIMIT 1\n) p ON TRUE\nLEFT JOIN LATERAL (\n  SELECT tracking_number, status FROM shipments\n  WHERE order_id = o.id ORDER BY created_at DESC LIMIT 1\n) s ON TRUE\nGROUP BY o.id, u.email, u.first_name, u.last_name,\n  p.status, p.payment_method, s.tracking_number, s.status;"}' "V33"

# V34
post '{"description":"Create daily sales dashboard view","sqlContent":"CREATE OR REPLACE VIEW v_daily_sales AS\nSELECT\n  DATE(o.placed_at) AS sale_date,\n  COUNT(DISTINCT o.id) AS order_count,\n  COUNT(DISTINCT o.user_id) AS unique_customers,\n  SUM(o.subtotal) AS gross_revenue,\n  SUM(o.discount_amount) AS total_discounts,\n  SUM(o.tax_amount) AS total_tax,\n  SUM(o.shipping_amount) AS total_shipping,\n  SUM(o.total) AS net_revenue,\n  AVG(o.total) AS avg_order_value,\n  SUM(oi.quantity) AS total_units_sold\nFROM orders o\nLEFT JOIN order_items oi ON oi.order_id = o.id\nWHERE o.status NOT IN ('\''cancelled'\'', '\''refunded'\'')\nGROUP BY DATE(o.placed_at)\nORDER BY sale_date DESC;"}' "V34"

# V35
post '{"description":"Create customer lifetime value view","sqlContent":"CREATE OR REPLACE VIEW v_customer_lifetime_value AS\nSELECT\n  u.id AS user_id,\n  u.email,\n  u.first_name,\n  u.last_name,\n  u.created_at AS member_since,\n  COUNT(DISTINCT o.id) AS total_orders,\n  SUM(o.total) AS lifetime_value,\n  AVG(o.total) AS avg_order_value,\n  MIN(o.placed_at) AS first_order_at,\n  MAX(o.placed_at) AS last_order_at,\n  EXTRACT(DAY FROM MAX(o.placed_at) - MIN(o.placed_at)) AS customer_lifespan_days,\n  COUNT(DISTINCT DATE(o.placed_at)) AS distinct_order_days\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\n  AND o.status NOT IN ('\''cancelled'\'', '\''refunded'\'')\nGROUP BY u.id, u.email, u.first_name, u.last_name, u.created_at;"}' "V35"

# V36
post '{"description":"Create inventory status view","sqlContent":"CREATE OR REPLACE VIEW v_inventory_status AS\nSELECT\n  p.id AS product_id,\n  p.name AS product_name,\n  p.sku AS product_sku,\n  pv.id AS variant_id,\n  pv.name AS variant_name,\n  pv.sku AS variant_sku,\n  pv.stock_quantity,\n  pv.low_stock_threshold,\n  CASE\n    WHEN pv.stock_quantity = 0 THEN '\''out_of_stock'\''\n    WHEN pv.stock_quantity <= pv.low_stock_threshold THEN '\''low_stock'\''\n    ELSE '\''in_stock'\''\n  END AS stock_status,\n  COALESCE(il.warehouse_stock, '\''{}'\''::JSONB) AS warehouse_breakdown,\n  p.is_active AND pv.is_active AS is_sellable\nFROM products p\nJOIN product_variants pv ON pv.product_id = p.id\nLEFT JOIN LATERAL (\n  SELECT jsonb_object_agg(w.name, il2.quantity) AS warehouse_stock\n  FROM inventory_levels il2\n  JOIN inventory_locations w ON w.id = il2.location_id\n  WHERE il2.variant_id = pv.id\n) il ON TRUE;"}' "V36"

# V37
post '{"description":"Create top products view","sqlContent":"CREATE OR REPLACE VIEW v_top_products AS\nSELECT\n  p.id,\n  p.name,\n  p.sku,\n  p.base_price,\n  c.name AS category_name,\n  SUM(oi.quantity) AS total_units_sold,\n  SUM(oi.total_price) AS total_revenue,\n  COUNT(DISTINCT oi.order_id) AS order_count,\n  COALESCE(rv.avg_rating, 0) AS avg_rating,\n  COALESCE(rv.review_count, 0) AS review_count,\n  COALESCE(pv_agg.total_views, 0) AS total_views,\n  CASE WHEN COALESCE(pv_agg.total_views, 0) > 0\n    THEN (COUNT(DISTINCT oi.order_id)::NUMERIC / pv_agg.total_views * 100)::NUMERIC(5,2)\n    ELSE 0\n  END AS conversion_rate\nFROM products p\nLEFT JOIN categories c ON c.id = p.category_id\nLEFT JOIN order_items oi ON oi.product_id = p.id\nLEFT JOIN LATERAL (\n  SELECT AVG(rating)::NUMERIC(3,2) AS avg_rating, COUNT(*) AS review_count\n  FROM product_reviews WHERE product_id = p.id AND is_approved = TRUE\n) rv ON TRUE\nLEFT JOIN LATERAL (\n  SELECT COUNT(*) AS total_views FROM product_views WHERE product_id = p.id\n) pv_agg ON TRUE\nGROUP BY p.id, p.name, p.sku, p.base_price, c.name,\n  rv.avg_rating, rv.review_count, pv_agg.total_views\nORDER BY total_revenue DESC NULLS LAST;"}' "V37"

# V38
post '{"description":"Create coupon usage analytics view","sqlContent":"CREATE OR REPLACE VIEW v_coupon_analytics AS\nSELECT\n  c.id,\n  c.code,\n  c.description,\n  c.discount_type,\n  c.discount_value,\n  c.usage_limit,\n  c.usage_count,\n  c.starts_at,\n  c.expires_at,\n  c.is_active,\n  COALESCE(stats.times_used, 0) AS actual_uses,\n  COALESCE(stats.total_discount_given, 0) AS total_discount_given,\n  COALESCE(stats.total_order_value, 0) AS total_order_value_with_coupon,\n  CASE WHEN COALESCE(stats.total_order_value, 0) > 0\n    THEN (stats.total_discount_given / stats.total_order_value * 100)::NUMERIC(5,2)\n    ELSE 0\n  END AS discount_rate_pct\nFROM coupons c\nLEFT JOIN LATERAL (\n  SELECT\n    COUNT(*) AS times_used,\n    SUM(oc.discount_applied) AS total_discount_given,\n    SUM(o.total) AS total_order_value\n  FROM order_coupons oc\n  JOIN orders o ON o.id = oc.order_id\n  WHERE oc.coupon_id = c.id\n) stats ON TRUE;"}' "V38"

# V39
post '{"description":"Create user activity overview view","sqlContent":"CREATE OR REPLACE VIEW v_user_activity AS\nSELECT\n  u.id,\n  u.email,\n  u.username,\n  u.first_name,\n  u.last_name,\n  u.created_at AS registered_at,\n  u.last_login_at,\n  u.is_active,\n  COALESCE(o_stats.order_count, 0) AS order_count,\n  COALESCE(o_stats.total_spent, 0) AS total_spent,\n  COALESCE(r_stats.review_count, 0) AS review_count,\n  COALESCE(w_stats.wishlist_item_count, 0) AS wishlist_items,\n  COALESCE(n_stats.unread_notifications, 0) AS unread_notifications,\n  s.last_active_at AS last_session_activity\nFROM users u\nLEFT JOIN LATERAL (\n  SELECT COUNT(*) AS order_count, SUM(total) AS total_spent\n  FROM orders WHERE user_id = u.id AND status != '\''cancelled'\''\n) o_stats ON TRUE\nLEFT JOIN LATERAL (\n  SELECT COUNT(*) AS review_count FROM product_reviews WHERE user_id = u.id\n) r_stats ON TRUE\nLEFT JOIN LATERAL (\n  SELECT COUNT(*) AS wishlist_item_count\n  FROM wishlist_items wi JOIN wishlists w ON w.id = wi.wishlist_id\n  WHERE w.user_id = u.id\n) w_stats ON TRUE\nLEFT JOIN LATERAL (\n  SELECT COUNT(*) AS unread_notifications\n  FROM notifications WHERE user_id = u.id AND is_read = FALSE\n) n_stats ON TRUE\nLEFT JOIN LATERAL (\n  SELECT last_active_at FROM user_sessions\n  WHERE user_id = u.id ORDER BY last_active_at DESC LIMIT 1\n) s ON TRUE;"}' "V39"

# V40
post '{"description":"Create shipping performance view","sqlContent":"CREATE OR REPLACE VIEW v_shipping_performance AS\nSELECT\n  sm.id AS method_id,\n  sm.name AS method_name,\n  sm.carrier,\n  COUNT(s.id) AS total_shipments,\n  AVG(EXTRACT(EPOCH FROM (s.delivered_at - s.shipped_at)) / 3600)::NUMERIC(6,1) AS avg_delivery_hours,\n  MIN(EXTRACT(EPOCH FROM (s.delivered_at - s.shipped_at)) / 3600)::NUMERIC(6,1) AS min_delivery_hours,\n  MAX(EXTRACT(EPOCH FROM (s.delivered_at - s.shipped_at)) / 3600)::NUMERIC(6,1) AS max_delivery_hours,\n  COUNT(CASE WHEN s.status = '\''delivered'\'' THEN 1 END) AS delivered_count,\n  COUNT(CASE WHEN s.status = '\''pending'\'' THEN 1 END) AS pending_count,\n  CASE WHEN COUNT(s.id) > 0\n    THEN (COUNT(CASE WHEN s.status = '\''delivered'\'' THEN 1 END)::NUMERIC / COUNT(s.id) * 100)::NUMERIC(5,2)\n    ELSE 0\n  END AS delivery_rate_pct\nFROM shipping_methods sm\nLEFT JOIN shipments s ON s.shipping_method_id = sm.id\nGROUP BY sm.id, sm.name, sm.carrier;"}' "V40"

# V41
post '{"description":"Create return analytics view","sqlContent":"CREATE OR REPLACE VIEW v_return_analytics AS\nSELECT\n  DATE_TRUNC('\''month'\'', r.requested_at) AS month,\n  COUNT(r.id) AS total_returns,\n  COUNT(CASE WHEN r.status = '\''refunded'\'' THEN 1 END) AS refunded_count,\n  COUNT(CASE WHEN r.status = '\''rejected'\'' THEN 1 END) AS rejected_count,\n  SUM(ri.refund_amount) AS total_refunded_amount,\n  AVG(EXTRACT(DAY FROM r.refunded_at - r.requested_at))::NUMERIC(5,1) AS avg_resolution_days,\n  COUNT(DISTINCT r.user_id) AS unique_returners,\n  r.reason,\n  COUNT(*) OVER (PARTITION BY r.reason ORDER BY DATE_TRUNC('\''month'\'', r.requested_at)) AS reason_running_total\nFROM returns r\nLEFT JOIN return_items ri ON ri.return_id = r.id\nGROUP BY DATE_TRUNC('\''month'\'', r.requested_at), r.reason;"}' "V41"

# V42
post '{"description":"Create category performance view","sqlContent":"CREATE OR REPLACE VIEW v_category_performance AS\nSELECT\n  c.id AS category_id,\n  c.name AS category_name,\n  c.slug AS category_slug,\n  parent.name AS parent_category,\n  COUNT(DISTINCT p.id) AS product_count,\n  COUNT(DISTINCT CASE WHEN p.is_active THEN p.id END) AS active_product_count,\n  COALESCE(SUM(oi.total_price), 0) AS total_revenue,\n  COALESCE(SUM(oi.quantity), 0) AS total_units_sold,\n  COALESCE(AVG(p.base_price), 0)::NUMERIC(12,2) AS avg_product_price,\n  COALESCE(MIN(p.base_price), 0)::NUMERIC(12,2) AS min_product_price,\n  COALESCE(MAX(p.base_price), 0)::NUMERIC(12,2) AS max_product_price,\n  COALESCE(rv.avg_category_rating, 0) AS avg_category_rating\nFROM categories c\nLEFT JOIN categories parent ON parent.id = c.parent_id\nLEFT JOIN products p ON p.category_id = c.id\nLEFT JOIN order_items oi ON oi.product_id = p.id\nLEFT JOIN LATERAL (\n  SELECT AVG(rating)::NUMERIC(3,2) AS avg_category_rating\n  FROM product_reviews pr\n  JOIN products p2 ON p2.id = pr.product_id\n  WHERE p2.category_id = c.id AND pr.is_approved = TRUE\n) rv ON TRUE\nGROUP BY c.id, c.name, c.slug, parent.name, rv.avg_category_rating;"}' "V42"

# V43
post '{"description":"Create abandoned carts view","sqlContent":"CREATE OR REPLACE VIEW v_abandoned_carts AS\nSELECT\n  sc.id AS cart_id,\n  sc.user_id,\n  u.email,\n  u.first_name,\n  sc.created_at AS cart_created_at,\n  sc.updated_at AS last_activity,\n  EXTRACT(HOUR FROM NOW() - sc.updated_at)::INTEGER AS hours_since_activity,\n  COUNT(ci.id) AS item_count,\n  SUM(ci.quantity) AS total_units,\n  SUM(ci.unit_price * ci.quantity)::NUMERIC(12,2) AS cart_value,\n  jsonb_agg(jsonb_build_object(\n    '\''product'\'', pv.name,\n    '\''quantity'\'', ci.quantity,\n    '\''price'\'', ci.unit_price\n  )) AS cart_contents\nFROM shopping_carts sc\nJOIN cart_items ci ON ci.cart_id = sc.id\nJOIN product_variants pv ON pv.id = ci.variant_id\nLEFT JOIN users u ON u.id = sc.user_id\nWHERE sc.updated_at < NOW() - INTERVAL '\''1 hour'\''\n  AND NOT EXISTS (\n    SELECT 1 FROM orders o WHERE o.user_id = sc.user_id\n    AND o.placed_at > sc.created_at\n  )\nGROUP BY sc.id, sc.user_id, u.email, u.first_name,\n  sc.created_at, sc.updated_at;"}' "V43"

# V44
post '{"description":"Create gift card balance view","sqlContent":"CREATE OR REPLACE VIEW v_gift_card_overview AS\nSELECT\n  gc.id,\n  gc.code,\n  gc.initial_balance,\n  gc.current_balance,\n  gc.currency_code,\n  gc.is_active,\n  gc.expires_at,\n  gc.created_at,\n  purchaser.email AS purchaser_email,\n  gc.recipient_email,\n  gc.recipient_name,\n  COALESCE(tx.transaction_count, 0) AS transaction_count,\n  COALESCE(tx.total_spent, 0) AS total_amount_used,\n  (gc.initial_balance - gc.current_balance)::NUMERIC(12,2) AS amount_used,\n  CASE\n    WHEN gc.current_balance = 0 THEN '\''depleted'\''\n    WHEN gc.expires_at < NOW() THEN '\''expired'\''\n    WHEN NOT gc.is_active THEN '\''disabled'\''\n    ELSE '\''active'\''\n  END AS card_status\nFROM gift_cards gc\nLEFT JOIN users purchaser ON purchaser.id = gc.purchaser_id\nLEFT JOIN LATERAL (\n  SELECT COUNT(*) AS transaction_count, SUM(ABS(amount)) AS total_spent\n  FROM gift_card_transactions\n  WHERE gift_card_id = gc.id AND type = '\''charge'\''\n) tx ON TRUE;"}' "V44"

# V45
post '{"description":"Create webhook health view","sqlContent":"CREATE OR REPLACE VIEW v_webhook_health AS\nSELECT\n  w.id,\n  w.url,\n  w.events,\n  w.is_active,\n  w.failure_count,\n  w.last_triggered_at,\n  COALESCE(d.total_deliveries, 0) AS total_deliveries,\n  COALESCE(d.successful_deliveries, 0) AS successful_deliveries,\n  COALESCE(d.failed_deliveries, 0) AS failed_deliveries,\n  CASE WHEN COALESCE(d.total_deliveries, 0) > 0\n    THEN (d.successful_deliveries::NUMERIC / d.total_deliveries * 100)::NUMERIC(5,2)\n    ELSE 100\n  END AS success_rate_pct,\n  COALESCE(d.avg_duration_ms, 0) AS avg_response_time_ms,\n  d.last_delivery_at,\n  d.last_status_code\nFROM webhooks w\nLEFT JOIN LATERAL (\n  SELECT\n    COUNT(*) AS total_deliveries,\n    COUNT(CASE WHEN success THEN 1 END) AS successful_deliveries,\n    COUNT(CASE WHEN NOT success THEN 1 END) AS failed_deliveries,\n    AVG(duration_ms)::INTEGER AS avg_duration_ms,\n    MAX(created_at) AS last_delivery_at,\n    (ARRAY_AGG(response_status ORDER BY created_at DESC))[1] AS last_status_code\n  FROM webhook_deliveries\n  WHERE webhook_id = w.id\n) d ON TRUE;"}' "V45"

# V46
post '{"description":"Create search analytics view","sqlContent":"CREATE OR REPLACE VIEW v_search_analytics AS\nSELECT\n  sq.query_text,\n  COUNT(*) AS search_count,\n  COUNT(DISTINCT sq.user_id) AS unique_searchers,\n  AVG(sq.results_count)::INTEGER AS avg_results,\n  COUNT(sq.clicked_product_id) AS click_count,\n  CASE WHEN COUNT(*) > 0\n    THEN (COUNT(sq.clicked_product_id)::NUMERIC / COUNT(*) * 100)::NUMERIC(5,2)\n    ELSE 0\n  END AS click_through_rate,\n  MIN(sq.created_at) AS first_searched_at,\n  MAX(sq.created_at) AS last_searched_at,\n  ARRAY_AGG(DISTINCT sq.clicked_product_id) FILTER (WHERE sq.clicked_product_id IS NOT NULL) AS clicked_products\nFROM search_queries sq\nGROUP BY sq.query_text\nORDER BY search_count DESC;"}' "V46"

echo ""
echo "Done! Checking final count..."
curl -s "http://localhost:3000/api/projects/$PROJECT_ID/migrations" | python3 -c "import sys,json; data=json.load(sys.stdin); print(f'Total migrations: {len(data)}')" 2>/dev/null || curl -s "http://localhost:3000/api/projects/$PROJECT_ID/migrations" | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>console.log('Total migrations:',JSON.parse(d).length))"
