import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Plus, FileCode } from 'lucide-react';
import * as api from '@/api/client';
import { useToast } from '@/components/ui/use-toast';

interface MigrationTemplate {
  id: string;
  label: string;
  description: string;
  sql: string;
}

const TEMPLATES: MigrationTemplate[] = [
  {
    id: 'blank',
    label: 'Blank',
    description: 'Empty migration',
    sql: '-- Write your migration SQL here\n',
  },
  {
    id: 'create-table',
    label: 'Create Table',
    description: 'Create a new table with common columns',
    sql: `CREATE TABLE IF NOT EXISTS table_name (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);\n`,
  },
  {
    id: 'add-column',
    label: 'Add Column',
    description: 'Add a column to an existing table',
    sql: `ALTER TABLE table_name
  ADD COLUMN column_name VARCHAR(255);\n`,
  },
  {
    id: 'create-index',
    label: 'Create Index',
    description: 'Create an index concurrently',
    sql: `CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_table_column
  ON table_name (column_name);\n`,
  },
  {
    id: 'create-enum',
    label: 'Create Enum',
    description: 'Create a PostgreSQL enum type',
    sql: `CREATE TYPE status_type AS ENUM ('active', 'inactive', 'pending');\n`,
  },
  {
    id: 'add-fk',
    label: 'Add Foreign Key',
    description: 'Add a foreign key constraint',
    sql: `ALTER TABLE child_table
  ADD CONSTRAINT fk_child_parent
  FOREIGN KEY (parent_id)
  REFERENCES parent_table (id)
  ON DELETE CASCADE;\n`,
  },
  {
    id: 'create-function',
    label: 'Create Function',
    description: 'Create a PL/pgSQL function',
    sql: `CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_table_name_updated_at
  BEFORE UPDATE ON table_name
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();\n`,
  },
  {
    id: 'create-view',
    label: 'Create View',
    description: 'Create a database view',
    sql: `CREATE OR REPLACE VIEW view_name AS
SELECT
  t.id,
  t.name,
  t.created_at
FROM table_name t
WHERE t.is_active = TRUE;\n`,
  },
];

interface CreateMigrationDialogProps {
  projectId: string;
  onCreated: () => void;
}

/**
 * Dialog for creating a new migration with description and optional template.
 * Version number is auto-generated by the backend.
 */
export function CreateMigrationDialog({ projectId, onCreated }: CreateMigrationDialogProps) {
  const [open, setOpen] = useState(false);
  const [description, setDescription] = useState('');
  const [selectedTemplate, setSelectedTemplate] = useState('blank');
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!description.trim()) return;

    const template = TEMPLATES.find((t) => t.id === selectedTemplate) || TEMPLATES[0];

    try {
      setLoading(true);
      await api.createMigration(projectId, {
        description: description.trim(),
        sqlContent: template.sql,
      });
      toast({ title: 'Migration created', description: `"${description.trim()}" has been created.` });
      setDescription('');
      setSelectedTemplate('blank');
      setOpen(false);
      onCreated();
    } catch (err: any) {
      toast({ title: 'Error', description: err.message, variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline">
          <Plus className="mr-2 h-4 w-4" />
          New Migration
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-lg">
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>Create New Migration</DialogTitle>
            <DialogDescription>
              Choose a template and enter a description. Version number is auto-assigned.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <Label htmlFor="migration-desc">Description</Label>
              <Input
                id="migration-desc"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="e.g., Create users table"
                className="mt-1"
                autoFocus
              />
            </div>
            <div>
              <Label>Template</Label>
              <div className="mt-1 grid grid-cols-2 gap-2">
                {TEMPLATES.map((t) => (
                  <button
                    key={t.id}
                    type="button"
                    onClick={() => setSelectedTemplate(t.id)}
                    className={`flex items-start gap-2 rounded-md border p-2.5 text-left text-sm transition-colors ${
                      selectedTemplate === t.id
                        ? 'border-primary bg-primary/5 ring-1 ring-primary'
                        : 'border-border hover:border-primary/50 hover:bg-muted/50'
                    }`}
                  >
                    <FileCode className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
                    <div>
                      <div className="font-medium text-foreground">{t.label}</div>
                      <div className="text-xs text-muted-foreground">{t.description}</div>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={!description.trim() || loading}>
              {loading ? 'Creating...' : 'Create'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
